# Generated by Django 3.1 on 2021-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirectCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcompany',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directcompany',
            name='city',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directcompany',
            name='country',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directcompany',
            name='email',
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directcompany',
            name='tel',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
