# Generated by Django 3.1 on 2021-03-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DirectCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regie', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=4)),
                ('direct_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DirectCompany.directcompany')),
            ],
        ),
    ]
