# Generated by Django 3.0 on 2021-02-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('AffiliateCompany', '0001_initial'),
        ('DirectCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direct_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DirectCompany.DirectCompany')),
            ],
        ),
        migrations.CreateModel(
            name='TransfoAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_bc', models.CharField(max_length=255)),
                ('affiliate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AffiliateCompany.AffiliateCompany')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Person')),
                ('transfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.Transfo')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('transfo_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transfo.TransfoAnalysis')),
            ],
        ),
    ]
