# Generated by Django 3.1 on 2021-03-08 22:36

import Transfo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poste', '0001_initial'),
        ('Transfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDVValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(choices=[('huile conforme', 'Huile conforme'), ('huile à traiter', 'Huile à traiter'), ('huile à changer', 'Huile à changer')], max_length=255)),
                ('recomendation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleBDVTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_value', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevelement_effectue_par', models.CharField(choices=[('nos soins', 'Nos soins'), ('vos soins', 'Vos soins')], max_length=255)),
                ('norme_de_prelevement', models.CharField(max_length=255)),
                ('temperature_de_fluide', models.CharField(max_length=255)),
                ('point_de_prelevement', models.CharField(max_length=255)),
                ('date_de_prevelement', models.CharField(max_length=255)),
                ('date_de_reception', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleCircumstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_dessais', models.JSONField(default=Transfo.models.get_raison_dessais_default_value)),
                ('etat_transfo', models.JSONField(default=Transfo.models.get_etat_transfo_default_value)),
                ('cuve_déformée', models.JSONField(default=Transfo.models.get_cuve_déformée_default_value)),
                ('alarme', models.JSONField(default=Transfo.models.get_alarme_default_value)),
                ('declenchement', models.JSONField(default=Transfo.models.get_declenchement_default_value)),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dessai', models.CharField(max_length=255)),
                ('appereil_dessaie', models.CharField(max_length=255)),
                ('frequence_dessai', models.CharField(max_length=255)),
                ('nombre_de_mesure', models.IntegerField()),
                ('Norme_dessai', models.CharField(max_length=255)),
                ('type_delectrodes', models.CharField(max_length=255)),
                ('distance_entre_electrodes', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='VisualObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=255)),
                ('presence_de_corps_en_suspension', models.JSONField(default=Transfo.models.get_presence_de_corps_en_suspension_default_value)),
            ],
        ),
        migrations.RemoveField(
            model_name='value',
            name='transfo_analysis',
        ),
        migrations.RenameField(
            model_name='transfo',
            old_name='name',
            new_name='annee_de_creation_primaire',
        ),
        migrations.RemoveField(
            model_name='transfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transfo',
            name='direct_company',
        ),
        migrations.AddField(
            model_name='transfo',
            name='commutateur_a_vide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfo',
            name='hermétique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfo',
            name='marque',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfo',
            name='masse_dhuile',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfo',
            name='mode_de_refroidissement_dhuile',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfo',
            name='nombre_de_man_oeuvre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfo',
            name='num_serie',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfo',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Poste.poste'),
        ),
        migrations.AddField(
            model_name='transfo',
            name='puissance',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfo',
            name='regleur_en_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfo',
            name='respirant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfo',
            name='tension',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TransfoAnalysis',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.AddField(
            model_name='sample',
            name='bdv_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplebdvtest'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_characteristics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplecharacteristics'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_circumstances',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplecircumstances'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_test_characteristics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transfo.sampletestcharacteristics'),
        ),
        migrations.AddField(
            model_name='sample',
            name='transfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transfo.transfo'),
        ),
        migrations.AddField(
            model_name='sample',
            name='visual_observations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transfo.visualobservations'),
        ),
        migrations.AddField(
            model_name='bdvvalue',
            name='sample_bdv_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplebdvtest'),
        ),
    ]
