# Generated by Django 3.1 on 2021-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0002_auto_20210308_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfo',
            name='date_de_fabriquation',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
