# Generated by Django 3.1 on 2021-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0003_transfo_date_de_fabriquation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfo',
            name='date_de_fabriquation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
