# Generated by Django 3.1 on 2021-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0004_auto_20210310_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfo',
            old_name='hermétique',
            new_name='hermetique',
        ),
    ]
