# Generated by Django 3.1 on 2021-03-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0005_auto_20210311_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfo',
            old_name='nombre_de_man_oeuvre',
            new_name='nombre_de_man_doeuvre',
        ),
    ]
