# Generated by Django 3.1 on 2021-03-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0007_auto_20210311_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfo',
            old_name='annee_de_creation_primaire',
            new_name='annee_de_fabrication_primaire',
        ),
    ]
