# Generated by Django 3.1 on 2021-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0008_auto_20210311_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfo',
            name='annee_de_fabrication_primaire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfo',
            name='date_de_fabriquation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfo',
            name='puissance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfo',
            name='tension',
            field=models.IntegerField(default=0),
        ),
    ]
