# Generated by Django 3.1 on 2021-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0009_auto_20210321_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfo',
            old_name='annee_de_fabrication_primaire',
            new_name='tension_primaire',
        ),
        migrations.RemoveField(
            model_name='transfo',
            name='tension',
        ),
    ]
