# Generated by Django 3.1 on 2021-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0010_auto_20210321_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecharacteristics',
            name='norme_de_prelevement',
        ),
        migrations.AlterField(
            model_name='samplecharacteristics',
            name='date_de_prevelement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='samplecharacteristics',
            name='prevelement_effectue_par',
            field=models.CharField(choices=[('nos soins selon le norme CEI 60475', 'Nos soins'), ('vos soins', 'Vos soins')], max_length=255),
        ),
    ]
