# Generated by Django 3.1 on 2021-03-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20210308_2336'),
        ('AffiliateCompany', '0004_auto_20210321_1615'),
        ('Transfo', '0011_auto_20210321_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='affiliate_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AffiliateCompany.affiliatecompany'),
        ),
        migrations.AddField(
            model_name='sample',
            name='num_bc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.person'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bdv_test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplebdvtest'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='conclusion',
            field=models.CharField(blank=True, choices=[('huile conforme', 'Huile conforme'), ('huile à traiter', 'Huile à traiter'), ('huile à changer', 'Huile à changer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplecharacteristics'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_circumstances',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.samplecircumstances'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_test_characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.sampletestcharacteristics'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='visual_observations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transfo.visualobservations'),
        ),
    ]
