# Generated by Django 3.1 on 2021-03-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfo', '0012_auto_20210321_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecharacteristics',
            name='temperature_de_fluide',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
